baseurl: "" 
url: "https://turtlecoin.lol"

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - Rakefile
 - README.md
 - .bundle
 - vendor

gems:
 - jekyll-multiple-languages-plugin

# Localization config

languages: ["en", "es", "pt-br", "de", "el"]

language_names:
  en:
    short: en
    full: English
  es:
    short: es
    full: Español
  pt-br:
    short: pt-br
    full: Portuguese
  de:
    short: de
    full: Deutsch
  el:
    short: el
    full: Ελληνικά 
  # dev:
  #   short: dev
  #   full: Development


# couldn't make this work 
# exclude_from_localizations: ["assets"]
